{
  imports = [
    ./essential/spell.nix
    ./essential/shell.nix
    ./dev/git.nix
    ./dev/latex.nix
    ./dev/java.nix
    ./colorschemes/dracula.nix
    ./desktop/office.nix
    #./desktop/notification.nix
    ./desktop/fonts.nix
    ./desktop/alacritty.nix
    ./desktop/rofi.nix
    ./editors/emacs.nix
    ./editors/neovim.nix
    ./desktop/discord.nix
    ./desktop/firefox
    ./desktop/steam.nix
    ./desktop/email.nix
  ];
}
